#

In [1]:
options(jupyter.rich_display = FALSE)

# Assignment 1: R Basics and Control Flow

## POP77001 Computer Programming for Social Scientists

## Before Submission

-   Make sure that you can run all cells without errors
-   You can do it by clicking `Kernel`, `Restart & Run All` in the menu
    above
-   Make sure that you save the output by pressing Command+S / CTRL+S
-   Rename the file from `01_assignment.ipynb` to
    `01_assignment_lastname_firstname_studentnumber.ipynb`
-   Use Firefox browser for submitting your Jupyter notebook on
    Blackboard.

## Exercise 1: Subsetting

Write 5 separate subsetting operations to extract the following elements
from the list below: - All consonants from the first character vector; -
Second columns in all dimensions from the array `A`; - Odd rows from the
matrix `M`; - P-value from the results of t-test `test`; - Estimates of
the 3 coefficients from the linear regression fit `model`.

Tip: Use `str()` function to inspect the structure of R objects.

In [2]:
set.seed(2023)
l <- list(
  mapply(assign, letters, 1:26),
  A = array(1:60, c(5,2,3)),
  M = matrix(1:50, c(10,5)),
  test = t.test(rnorm(100, -1), rnorm(100, 2)),
  model = lm(
    y ~ x + z,
    data = list(y = rnorm(100), x = rnorm(100), z = rnorm(100))
  )
)

In [4]:
l

[[1]]
 a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

$A
, , 1

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

, , 2

     [,1] [,2]
[1,]   11   16
[2,]   12   17
[3,]   13   18
[4,]   14   19
[5,]   15   20

, , 3

     [,1] [,2]
[1,]   21   26
[2,]   22   27
[3,]   23   28
[4,]   24   29
[5,]   25   30


$M
      [,1] [,2] [,3] [,4] [,5]
 [1,]    1   11   21   31   41
 [2,]    2   12   22   32   42
 [3,]    3   13   23   33   43
 [4,]    4   14   24   34   44
 [5,]    5   15   25   35   45
 [6,]    6   16   26   36   46
 [7,]    7   17   27   37   47
 [8,]    8   18   28   38   48
 [9,]    9   19   29   39   49
[10,]   10   20   30   40   50

$test

	Welch Two Sample t-test

data:  rnorm(100, -1) and rnorm(100, 2)
t = -23.01, df = 197.32, p-value < 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percen

In [5]:
# Exercise 1:

# Your code goes here

# - All consonants from the first character vector
first_vector <- l[[1]] # Extract the vector from l
all_consonants <- first_vector[-c(1, 5, 9, 15, 21)] # Eliminate 5 vowels
print(all_consonants) # Print all consonants

# - Second columns in all dimensions from the array `A`
second_array <- l[[2]] # Extract the array from l
second_columns <- second_array[ , 2, , drop = FALSE] # Extract the 2nd columns
print(second_columns) # Print the second columns

# - Odd rows from the matrix `M`
third_matrix <- l[[3]] # Extract the matrix from l

row_number <- 1 : nrow(third_matrix) # Get the number of rows in the matrix
odd_number <- row_number[row_number %% 2 == 1] # Get odd number in upper vector

odd_row <- third_matrix[odd_number, ] # Extract the odd rows from the matrix
print(odd_row) # Print the odd rows

# - P-value from the results of t-test `test`
n1 <- 100 ; n2 <- 100 # According to the code, the amount are both 100
mean1 <- -1 ; mean2 <- 2 # According to the code, x bar1 is -1, and x bar2 is 2
sd1 <- 1 ; sd2 <- 1 # According to the code, the sd are both 1

se <- sqrt((sd1^2 / n1) + (sd2^2 / n2)) # Calculate the standard error
t_value <- (mean1 - mean2) / se # Calcuate the t value
p_value <- pt(t_value, df <- n1 + n2 - 2) # Calculate p value in df n1+n2-2
print(p_value) # Print the p value

# - Estimates of the 3 coefficients from the linear regression fit `model`

regression_model <- l[[5]] # Extract the regression model from l
print("The 3 coefficients from the model are printed below: ")
print(summary(regression_model)$coefficients)

 b  c  d  f  g  h  j  k  l  m  n  p  q  r  s  t  v  w  x  y  z 
 2  3  4  6  7  8 10 11 12 13 14 16 17 18 19 20 22 23 24 25 26 
, , 1

     [,1]
[1,]    6
[2,]    7
[3,]    8
[4,]    9
[5,]   10

, , 2

     [,1]
[1,]   16
[2,]   17
[3,]   18
[4,]   19
[5,]   20

, , 3

     [,1]
[1,]   26
[2,]   27
[3,]   28
[4,]   29
[5,]   30

     [,1] [,2] [,3] [,4] [,5]
[1,]    1   11   21   31   41
[2,]    3   13   23   33   43
[3,]    5   15   25   35   45
[4,]    7   17   27   37   47
[5,]    9   19   29   39   49


[1] 3.582517e-53
[1] "The 3 coefficients from the model are printed below: "
               Estimate Std. Error    t value  Pr(>|t|)
(Intercept) -0.16453134 0.10020225 -1.6419924 0.1038299
x           -0.08069619 0.09952588 -0.8108061 0.4194620
z           -0.03880831 0.10584141 -0.3666647 0.7146677


## Exercise 2: Working with Vectors

Look at the vector below. What is its type? Convert it into numeric.
Note that some values get missing due to letter `o` used instead of
digit `0`. What proportion of the vector elements did we fail to convert
correctly? Now let us fix this issue. Using either subsetting and
assignment or `ifelse()` function replace all `NA`s in the converted
numeric vector into `0` (zeros).

In [6]:
set.seed(2023)
vec <- sample(c("1", "0", "o"), size = 100, replace = TRUE)

In [7]:
# Exercise 2:

# Your code goes here

# This code is to confirm the type of vector
print(paste("The type of the vector is", typeof(vec))) # Print type of vector

# These codes are to convert the type of vector
numeric_vec <- as.numeric(vec) # Convert the type of vector into numeric
print(paste("The type of the new vector is",
            typeof(numeric_vec))) # Print type of vector

# These codes are to make sure the proportion of NA
# Because "NA == NA" is NA, so I use "!= 1 & != 0" to extract NA in vector
na_vector <- numeric_vec[numeric_vec != 1 & numeric_vec != 0]
print(paste("We fail to convert",
            length(na_vector),
            "% of vector elements correctly")) # Print the NA proportion

# These codes are to convert NA into 0
numeric_vec[is.na(numeric_vec)] <- 0 # Locate NA in vector and transfer into 0
print(numeric_vec) # Print the vector and check


[1] "The type of the vector is character"


Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"


[1] "The type of the new vector is double"
[1] "We fail to convert 29 % of vector elements correctly"
  [1] 1 0 1 0 0 0 1 1 1 1 1 1 1 0 0 0 0 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0
 [38] 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0
 [75] 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1 0 0 0 0 0


## Exercise 3: Vectorized Operations

Using function `mean()` calculate the percentage of book titles in the
vector below that have more than 10 characters in them (including
whitespaces).

Replace titles that are longer than 15 characters with `"Long Title"`.

Tip: You can use `nchar()` function to calculate the number of
characters in a vector

In [8]:
books <- c(
  "Dubliners",
  "The Picture of Dorian Gray",
  "Ulysses",
  "War and Peace",
  "Normal People",
  "Crime and Punishment",
  "Pygmalion"
)

In [9]:
# Exercise 3:

# Your code goes here

# Use a loop to mark book titles character > 10 as 1 and <= 10 is 0
char_number <- c()
for (i in books){
  if (nchar(i) > 10) {
    char_number <- c(char_number, 1)
  } else {
    char_number <- c(char_number, 0)
  }
}

# Count and print the mean in second columns, which refers to the proportion
print(paste("The proportion of more than 10 characters is ",
            round(mean(char_number), 2) * 100,
            "%"))

# If the second columns == 1, than replace the first columns into Long Title
books_char_number <- cbind(books, char_number)
books_char_number[ , 1][books_char_number[ , 2] == 1] <- "Long Title"
print(books_char_number[ , 1])


[1] "The proportion of more than 10 characters is  57 %"
[1] "Dubliners"  "Long Title" "Ulysses"    "Long Title" "Long Title"
[6] "Long Title" "Pygmalion" 


## Exercise 4: Attributes and Factors

Suppose you read in a variable which represents education of survey
respondents. After consulting the codebook for this survey you
determined that specific values that the variable takes are coded as
follows:

-   `0` - No formal education
-   `1` - Primary Education
-   `2` - Secondary Education
-   `3` - College Education
-   `4` - Post-graduate Education

Convert the variable `educ` below into a factor variable with each value
coded explicitly as one of the education levels. Tabulate the variable
using `table()` function. Change the order of the levels of this factor
variable such that the most common education level is the first
(baseline/reference) category (you can leave other education levels in
their original order). Tabulate the variable again.

In [10]:
set.seed(2023)
educ <- rpois(1000, 2)
educ <- ifelse(educ > 4, 4, educ)

In [11]:
# Exercise 4:

# Your code goes here

# Factorise educ, and label each value
unsorted_educ_with_labels <- factor(educ,
                                    levels <- c(0, 1, 2, 3, 4),
                                    labels <- c("No Formal Education",
                                                "Primary Education",
                                                "Secondary Education",
                                                "College Education",
                                                "Post-graduate Education"))
table_educ_01 <- table(unsorted_educ_with_labels) # Crate a table about educ
print(table_educ_01) # Print the unsorted table with labels

# I rewrote these code to make the two output tables have different titles
sorted_educ_with_labels <- unsorted_educ_with_labels
table_educ_02 <- table(sorted_educ_with_labels) # Create a table about educ
# Sorted educ with labels, and reverse the order
sorted_table_educ_02 <- table_educ_02[order(table_educ_02, decreasing = TRUE)]
print(sorted_table_educ_02) # Print the sorted table with labels


unsorted_educ_with_labels
    No Formal Education       Primary Education     Secondary Education 
                    142                     279                     278 
      College Education Post-graduate Education 
                    171                     130 
sorted_educ_with_labels
      Primary Education     Secondary Education       College Education 
                    279                     278                     171 
    No Formal Education Post-graduate Education 
                    142                     130 


## Exercise 5: Control Flow

[Skewness](https://en.wikipedia.org/wiki/Skewness) is an important
concept in data analysis. Many methods of statistical analysis assume
that the variables roughly follow a [normal
distribution](https://en.wikipedia.org/wiki/Normal_distribution).

In this exercise you will need to write R code to determine whether each
of the variables is approximately normally distributed and if not,
report the direction of skew (left/negative or right/positive). The
easiest way to do so is by comparing means and medians of the
distribution for each variable.

Look at the code below. Each variable is stored as a vector in a list.
Use loop(s) and conditional statements to analyse them.

In [12]:
set.seed(2023)
vars <- list(
  var1 = rexp(1000),
  var2 = rnorm(1000, -2.75, 3),
  var3 = rchisq(1000, 2),
  var4 = rt(1000, 30),
  var5 = rbeta(1000, 5, 2)
)

In [13]:
# Exercise 5:

# Your code goes here

# I use shapiro-test to test whether a variable obeys a normal distribution
for (i in vars) {
  norm_test_results <- shapiro.test(i) # Conduct shapiro-test
  print(norm_test_results) # Print the test results

  # Below is the shapiro-test hypothesis test progress
  # if p-value < 0.05, than it will not be a normal distribution
  if (norm_test_results$p.value < 0.05) {
    print("It is not a normal distribution")
    # if mean < median, it will be a left skew distribution
    if (mean(i) < median(i)) {
      print("It is a left skew distribution")
      # if mean > median, it will be a right skew distribution
    } else if (mean(i) > median(i)) {
      print("It is a right skew distribution")
    }
    # If p-value > 0.05, than it will be a normal distribution
  } else {
    print("It is a normal distribution")
  }
}



	Shapiro-Wilk normality test

data:  i
W = 0.82841, p-value < 2.2e-16

[1] "It is not a normal distribution"
[1] "It is a right skew distribution"

	Shapiro-Wilk normality test

data:  i
W = 0.9973, p-value = 0.09304

[1] "It is a normal distribution"

	Shapiro-Wilk normality test

data:  i
W = 0.81597, p-value < 2.2e-16

[1] "It is not a normal distribution"
[1] "It is a right skew distribution"

	Shapiro-Wilk normality test

data:  i
W = 0.99644, p-value = 0.02257

[1] "It is not a normal distribution"
[1] "It is a right skew distribution"

	Shapiro-Wilk normality test

data:  i
W = 0.9665, p-value = 2.1e-14

[1] "It is not a normal distribution"
[1] "It is a left skew distribution"
